trigger:
- main

pool: 
  name: Ravi-mohan-pipeline


jobs:
  - job: init
    steps:
    - script: terraform init


  - job: fmt
    steps:
    - script: terraform fmt


  - job: apply
    steps:
    - script: terraform apply

   
