trigger:
- main

pool: Ravi-mohan-pipeline

stages: 
- stage: Plan
  displayName: "Terraform Stage Plan"
  jobs:
  - job: terraform_init
    displayName: terraform initwa
    steps:
      - script: terraform init
        displayName: Terraform ko init karega

      - script: terraform validate
        displayName: Terraform ko validate karega

      - script: terraform plan
        displayName: Terraform ko plan karega



- stage:
  displayName: Terraform Apply
  dependsOn: plan
  jobs:
  - job: Apply
    displayName: Terraform apply karega 
    steps:
      - script: terraform apply
        displayName: Terraform ko apply karega 
   