trigger:
- main

pool:
  name: Ravi-mohan-pipeline

jobs:
  - job: terraform_plan
    displayName: "Terraform Plan"
    steps:
      - script: terraform init
        displayName: "Terraform Init"

     

      - script: terraform validate
        displayName: "Terraform Validate"

      - script: terraform plan -out=tfplan
        displayName: "Terraform Plan"

      # ✅ Publish tfplan as artifact
      - publish: tfplan
        artifact: tfplan-artifact

  - job: terraform_apply
    displayName: "Terraform Apply"
    dependsOn: terraform_plan
    
    steps:
      # ✅ Download tfplan artifact
      - download: current
        artifact: tfplan-artifact

      - script: terraform apply -auto-approve tfplan
        displayName: "Terraform Apply"
