trigger:
- main

pool:
  name: Ravi-mohan-pipeline

jobs:
  - job: terraform_plan
    displayName: "Terraform Plan"
    steps:
      - script: terraform init
        displayName: "Terraform Init"

      - script: terraform fmt -check -recursive
        displayName: "Terraform Format Check"

      - script: terraform validate
        displayName: "Terraform Validate"

      - script: terraform plan -out=tfplan
        displayName: "Terraform Plan"

  - job: terraform_apply
    displayName: "Terraform Apply"
    dependsOn: terraform_plan
    
    steps:
      - script: terraform apply -auto-approve tfplan
        displayName: "Terraform Apply"


   
